name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    stesp:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: unittest
      run: |
        python3 -m unittest discover -v
